name: ci 
on:
  push:
    branches:
      - main
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build EN platform docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.platform.yml
      - name: Build EN platform docs 10.0.0
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.platform_v10.0.0.yml    
      - name: Build EN itassist docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.itassist.yml    
      - name: Build JA platform docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.ja.platform.yml
      - name: Build JA itassist docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.ja.itassist.yml        
    

      # - name: Copy redirect index page
      #   run: sudo cp /index.html /site

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 
      - run: pip install mike --force-reinstall --verbose
      # - run: mike deploy --push --update-aliases 1.0 latest --ignore
      # - run: mkdocs gh-deploy --force
